import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import './cron';

import { cn } from '@/lib/utils';
import { Header } from '@/components/Header';
import { HeaderLogo } from '@/components/HeaderLogo';
import { QueryProvider } from '@/providers/query-provider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <QueryProvider>
          <Header>
            <HeaderLogo />
          </Header>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
